import "./main/add.js";
import "./main/clear.js";
import "./main/get.js";
import "./main/have.js";
import "./main/is.js";
import "./main/lock.js";
import "./main/remove.js";
import "./main/set.js";
import "./main/replace.js";
